import Foundation

enum MIDIConstants {
    static let ccNames: [UInt8: String] = [
        0: "Bank Select",
        1: "Mod Wheel",
        2: "Breath",
        3: "CC 3",
        4: "Foot Controller",
        5: "Portamento Time",
        6: "Data Entry MSB",
        7: "Volume",
        8: "Balance",
        9: "CC 9",
        10: "Pan",
        11: "Expression",
        12: "Effect 1",
        13: "Effect 2",
        14: "CC 14",
        15: "CC 15",
        16: "Gen Purpose 1",
        17: "Gen Purpose 2",
        18: "Gen Purpose 3",
        19: "Gen Purpose 4",
        64: "Sustain",
        65: "Portamento",
        66: "Sostenuto",
        67: "Soft Pedal",
        68: "Legato",
        69: "Hold 2",
        70: "Sound Variation",
        71: "Resonance",
        72: "Release Time",
        73: "Attack Time",
        74: "Cutoff",
        75: "Decay Time",
        76: "Vibrato Rate",
        77: "Vibrato Depth",
        78: "Vibrato Delay",
        79: "Sound Controller 10",
        80: "Gen Purpose 5",
        81: "Gen Purpose 6",
        82: "Gen Purpose 7",
        83: "Gen Purpose 8",
        84: "Portamento Control",
        91: "Reverb",
        92: "Tremolo",
        93: "Chorus",
        94: "Detune",
        95: "Phaser",
        96: "Data Increment",
        97: "Data Decrement",
        120: "All Sound Off",
        121: "Reset All",
        123: "All Notes Off",
    ]

    static func ccName(for number: UInt8) -> String {
        ccNames[number] ?? "CC \(number)"
    }
}
